<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $_helper = $this->helper('Smartwave\Porto\Helper\Data');
?>
<div class="block newsletter">
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="form_text-title">
                <h2>Get insider information</h2>
            </div>
            <div class="form_text-description">
                <span >Don`t miss out! Be the first to know about the latest news and promotions</span>
            </div>
            <div class="form_wrapper-field">
                <div class="field newsletter">
                    <label class="label" for="footer_newsletter"><span><?php echo __('Sign Up for Our Newsletter:') ?></span></label>
                    <div class="control">
                        <input name="email" type="email" id="footer_newsletter"
                               data-validate="{required:true, 'validate-email':true}" placeholder="<?php echo __('Enter your email address...');?>"/>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe primary" title="<?php echo __('Subscribe') ?>" type="submit">
                        <span><?php echo __('Subscribe') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
