
services:

  db:
    image: mariadb:10.6.20
    hostname: db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=magento
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    networks:
      net:

  search:
    image: elasticsearch:8.14.3
    hostname: search
    environment:
      - discovery.type=single-node
    networks:
      net:

  cache:
    image: redis:6.2.7
    hostname: cache
    networks:
      net:

  session:
    image: redis:6.2.7
    hostname: session
    networks:
      net:

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    hostname: ${COMPOSE_PROJECT_NAME}-docker
    ports:
      - "${HTTPS_PORT}:443"
    volumes:
      - ~/.composer:/var/www/html/.composer
      - ./app/etc/config.php:/var/www/html/app/etc/config.php
      - ./composer.lock:/var/www/html/composer.lock
    networks:
      net:
    depends_on:
      - db
      - cache
      - session

  varnish:
    build:
      context: .
      dockerfile: docker/Dockerfile.varnish
      args:
        VARNISH_CONFIG: ${VARNISH_CONFIG}
    hostname: varnish
    ports:
      - "${HTTP_PORT}:6081"
    networks:
      net:
    depends_on:
      - web

networks:
  net:


# vi:softtabstop=2:shiftwidth=2:
